### ISSUE TITLE
Remove the compile and run batch files from Git

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#10]
These files are specific to each individuals development environment and therefore should not be checked in to the repository.  Please remove these files from the repository so that I do not get conflicts when I pull.  The other option is that I can  start checking mine in so you get the conflicts when you pull.

**Comment by JaroschJr** [comment]
Acording to the website (<> Code) does not list any of them. They may simply be left over on your machine after I removed them form the cloud.
