### ISSUE TITLE
0009 - Generate and resolve the random event.

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#11]
The next thing in  the flow chart is to generate a random event and apply it.  Let me know if you wish to discuss this before starting to work on it, and we can talk on the phone some evening this week.

**Comment by JaroschJr** [comment]
would eight o-clock on Tuesday the 12 work?

**Comment by denn0134** [comment]
Yes

**Comment by denn0134** [comment]
Looks good, think about refactoring the switch statement in the MULTIPLY area to have less code repetition then close this one.  Also remove the default from the switches, or replace them with exceptions.

**Comment by denn0134** [comment]
Done
