### ISSUE TITLE
0009.01 Create random event classes

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#12]
Create stubs for all of the random event classes.

**Comment by denn0134** [comment]
Add the contructor, performEvent, and basic properties.

**Comment by JaroschJr** [comment]
I believe that I have addressed this, but I wanted someone else to look it over before closing the issue.

**Comment by denn0134** [comment]
Looking at the repository, I don't see any changes past the addition of the
event classes with the constructors which you commits 3 days ago.  If you
have added the properties and methods we discussed on Friday, you will need
to commit your changes for me to inspect them.

**Comment by JaroschJr** [comment]
It has been pushed now.

**Comment by denn0134** [comment]
Good start, you need to override the performEvent  method in all descendant
classes though (PLEASE: rename this without the misspelling, I wouldn't
make such a big deal about it except that this method will span numerous
classes and confusion can be avoided this way).  I also think you are
missing a property or two on the StatModifierEvent class.  I would also go
ahead and create the enumerations for the stat and production types so that
you can properly declare them in the classes.  It will be difficult for me
to do my work (i.e. creating the database table) until I know what the
property names are.

**Comment by JaroschJr** [comment]
And the enum for target stat and production go in RandomEvent?

**Comment by denn0134** [comment]
I added a comment to the issue.

**Comment by JaroschJr** [comment]
And these enums in a class, I import SCSEnum to it?

**Comment by denn0134** [comment]
I assume you are asking whether you need to import SCSEnums into
RandomEvent.java in order to use one of the enumerations as a variable in
the RandomEvent class?  If that isn't what you are asking please elaborate
on what you do mean.  If it is what you meant to ask, then I would have to
answer the question with a different question: What happened when you tried
it either way (importing it, or not importing it)?

**Comment by JaroschJr** [comment]
With no import, it said:
C:\Joey's coding stuf\SpaceColonySim\SpaceColonySim\RandomEvent.java:12:
error:
cannot find symbol
         eSign eSignExample = eSign.POSITIVE;
         ^
  symbol:   class eSign
  location: class RandomEvent
C:\Joey's coding stuf\SpaceColonySim\SpaceColonySim\RandomEvent.java:12:
error:
cannot find symbol
         eSign eSignExample = eSign.POSITIVE;
                              ^
  symbol:   variable eSign
  location: class RandomEvent
2 errors

I mimmicked the documentation here
https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaEnum.html

I was unsure how the importation itself was supposed to go. The class is
alled SCSEnum, so would it be
import SCSEnum.java;
import SCSEnum;
import java.SCSEnum;
or something else entirely? The compile errors from each of these is
helplessly cryptic, even more so than usual. The symbol not found error,
plus some variant of

C:\Joey's coding stuf\SpaceColonySim\SpaceColonySim\RandomEvent.java:1:
error:
 '.' expected
import SCSEnum;
                           ^

**Comment by JaroschJr** [comment]
Copies of all of the files are on the drive. I was unable to get it to
compile, due to difficulties with the Command Line Prompt, appointer of
headaches by royal decree.

**Comment by denn0134** [comment]
https://sqlitebrowser.org/  link to the sqlite browser application.

**Comment by JaroschJr** [comment]
This one, and the one after it, are to the best of my knowledge, completed. I would like you to check and close just to be sure- a problem missed now could cause us no end of grief later.

**Comment by denn0134** [comment]
Okay, this can now be considered closed.
