### ISSUE TITLE
0009.02 - Create eumerations for events

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#13]
Create enumerations for production type and stat type and for the random event classes

**Comment by denn0134** [comment]
Create a class which is specifically to hold these enumerations.  My suggestion for a name would be something like SCSEnums, but it is up to you.

**Comment by JaroschJr** [comment]
I belive I have done this as well. Close it if you agree.

**Comment by denn0134** [comment]
Looks reasonable.
