### ISSUE TITLE
0009.04 - Added sample random events.

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#15]
Please add AT LEAST two random events of each descendant event class so that we can create an event factory to create the event list in the application from the database.

**Comment by JaroschJr** [comment]
Should these be created and put in the data base, or as more examples in
the Engine?

**Comment by denn0134** [comment]
Add them to the database.

**Comment by denn0134** [comment]
Two sample events for ProductionMultiplyingEvent and StatModifierEvent added.  Need to finish adding the rest to the database.

**Comment by denn0134** [comment]
For now we will only worry about RandomEvent,, ProductionMultiplyingEvent and StatModifierEvent, so this is done, as we add the remaining event classes we will deal with them
