### ISSUE TITLE
0001 - Cleanup.

### ISSUE THREAD

**Issue by JaroschJr** [JaroschJr/SpaceColonySim#3]
Get rid of some of the stubbed method()s.

**Comment by denn0134** [comment]
I see you closed an issue.  Looking at the code on GitHub it looks as
though you haven't committed and/or synched your changes yet.  You
shouldn't close an issue until the code is up there.

**Comment by denn0134** [comment]
Join Zoom Meeting
https://us04web.zoom.us/j/73196876037?pwd=bi9LTnZIOEUvOHRCcDdZa3pyK0lEUT09

Meeting ID: 731 9687 6037
Passcode: dd8fnq
