### ISSUE TITLE
Milstone #1: Have game in shape to run it to the point where it creates a new game and informs the player if a trader is arriving on the first turn.

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#4]

**Comment by JaroschJr** [comment]
At the present moment, it can compile and run basic things without issue. We can being bulking it up more tomorrow and afterward.

**Comment by denn0134** [comment]
Don't be closing my issues!!!

**Comment by denn0134** [comment]
OK, looks good so far, except for the case sensitivity issue and the database path issue.
