### ISSUE TITLE
0007 Finish the LoadOrNew method.

### ISSUE THREAD

**Issue by denn0134** [JaroschJr/SpaceColonySim#8]
Looking at the flowchart, initialize should also include the first two boxes in the chart.  Setting the turn to 1, and determining the first turn of the freighter arrival.

**Comment by denn0134** [comment]
Make the changes stated above, but put them in the LoadOrNew method instead.

**Comment by denn0134** [comment]
Also make sure to initialize all of the game values (like how much of each resource, what the population is etc.)

**Comment by JaroschJr** [comment]
By the way, would you like the batch files in the rest of the things on
GitHub, or would you like it on Drive?

**Comment by denn0134** [comment]
You don't need to put the batch file anywhere special, they are to make
things easier for you.  If you have issues ad I need to see them, we will
deal with that then.

**Comment by JaroschJr** [comment]
Should the setting of SpaceColonyGame variables be done inside the LoadOrNew(), if the N is selected, or should it be put elsewhere, possibly in a method of its own?

**Comment by JaroschJr** [comment]
If i am interpreting it correctly, than the current version has this complete. And it does compile and run. If this is incomplete, tell me so. And if not, close it and give me my next orders.
